rails6-bookers2-debug-ruby3-main/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  # ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :users do
  member do
   get :followings, :followers
  end
end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
  resources :post_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end

rails6-bookers2-debug-ruby3-main/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

rails6-bookers2-debug-ruby3-main/app/helpers/searches_helper.rb
module SearchesHelper
end

rails6-bookers2-debug-ruby3-main/app/views/searches/_search.html.erb
<% if user_signed_in? %>
      <div class="search_form">
      <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
      </div>
    <% end %>

rails6-bookers2-debug-ruby3-main/app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
  <h1>Users search for <%= @word %></h1>
    <tbody>
      <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        <td><% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
        <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <h1>Books search for <%= @word %></h1>
    <tbody>
      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
      <% @books.each do |book| %>
        <tr>
          <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td>
           <% if book.favorited_by?(current_user) %>
         <p>
           <%= link_to book_favorites_path(book), method: :delete do %>
           ♥<%= book.favorites.count %> いいね
           <% end %>
         </p>
          <% else %>
         <p>
          <%= link_to book_favorites_path(book), method: :post do %>
          ♡<%= book.favorites.count %> いいね
          <% end %>
         </p>
         <% end %>
        </td>
        <td>
          <p><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></p>
        </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>